name: BetterThanSniffers
authors: [Ghostypeeps]
version: '0.0.1'
api-version: '1.21.8'
bootstrapper: me.ghostypeeps.betterThanSniffers.SnifferBootstrap
main: me.ghostypeeps.betterThanSniffers.BetterThanSniffers
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
    Geyser-Spigot:
      load: BEFORE
      required: true
