name: BetterThanSniffers
version: '0.0.1'
main: me.ghostypeeps.betterThanSniffers.BetterThanSniffers
api-version: '1.21.8'
authors: [ Ghostypeeps ]
commands:
  better-than-sniffers:
    description: Better Than Sniffers base command. Contains a bunch of random debug stuff.
    aliases: bts
    usage: /better-than-sniffers <args>
depend: [Geyser-Spigot]
